// Code generated by ent, DO NOT EDIT.

package instance

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the instance type in the database.
	Label = "instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "uuid"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// EdgeConfig holds the string denoting the config edge name in mutations.
	EdgeConfig = "config"
	// Table holds the table name of the instance in the database.
	Table = "instances"
	// ConfigTable is the table that holds the config relation/edge.
	ConfigTable = "instance_configs"
	// ConfigInverseTable is the table name for the InstanceConfig entity.
	// It exists in this package in order to avoid circular dependency with the "instanceconfig" package.
	ConfigInverseTable = "instance_configs"
	// ConfigColumn is the table column denoting the config relation/edge.
	ConfigColumn = "instance_config"
)

// Columns holds all SQL columns for instance fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
