// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sergot/tibiago/ent/instance"
	"github.com/sergot/tibiago/ent/instanceconfig"
	"github.com/sergot/tibiago/ent/predicate"
)

// InstanceConfigQuery is the builder for querying InstanceConfig entities.
type InstanceConfigQuery struct {
	config
	limit        *int
	offset       *int
	unique       *bool
	order        []OrderFunc
	fields       []string
	predicates   []predicate.InstanceConfig
	withInstance *InstanceQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InstanceConfigQuery builder.
func (icq *InstanceConfigQuery) Where(ps ...predicate.InstanceConfig) *InstanceConfigQuery {
	icq.predicates = append(icq.predicates, ps...)
	return icq
}

// Limit adds a limit step to the query.
func (icq *InstanceConfigQuery) Limit(limit int) *InstanceConfigQuery {
	icq.limit = &limit
	return icq
}

// Offset adds an offset step to the query.
func (icq *InstanceConfigQuery) Offset(offset int) *InstanceConfigQuery {
	icq.offset = &offset
	return icq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (icq *InstanceConfigQuery) Unique(unique bool) *InstanceConfigQuery {
	icq.unique = &unique
	return icq
}

// Order adds an order step to the query.
func (icq *InstanceConfigQuery) Order(o ...OrderFunc) *InstanceConfigQuery {
	icq.order = append(icq.order, o...)
	return icq
}

// QueryInstance chains the current query on the "instance" edge.
func (icq *InstanceConfigQuery) QueryInstance() *InstanceQuery {
	query := &InstanceQuery{config: icq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := icq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := icq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(instanceconfig.Table, instanceconfig.FieldID, selector),
			sqlgraph.To(instance.Table, instance.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, instanceconfig.InstanceTable, instanceconfig.InstanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(icq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first InstanceConfig entity from the query.
// Returns a *NotFoundError when no InstanceConfig was found.
func (icq *InstanceConfigQuery) First(ctx context.Context) (*InstanceConfig, error) {
	nodes, err := icq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{instanceconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (icq *InstanceConfigQuery) FirstX(ctx context.Context) *InstanceConfig {
	node, err := icq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InstanceConfig ID from the query.
// Returns a *NotFoundError when no InstanceConfig ID was found.
func (icq *InstanceConfigQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = icq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{instanceconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (icq *InstanceConfigQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := icq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InstanceConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one InstanceConfig entity is found.
// Returns a *NotFoundError when no InstanceConfig entities are found.
func (icq *InstanceConfigQuery) Only(ctx context.Context) (*InstanceConfig, error) {
	nodes, err := icq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{instanceconfig.Label}
	default:
		return nil, &NotSingularError{instanceconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (icq *InstanceConfigQuery) OnlyX(ctx context.Context) *InstanceConfig {
	node, err := icq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InstanceConfig ID in the query.
// Returns a *NotSingularError when more than one InstanceConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (icq *InstanceConfigQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = icq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{instanceconfig.Label}
	default:
		err = &NotSingularError{instanceconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (icq *InstanceConfigQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := icq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InstanceConfigs.
func (icq *InstanceConfigQuery) All(ctx context.Context) ([]*InstanceConfig, error) {
	if err := icq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return icq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (icq *InstanceConfigQuery) AllX(ctx context.Context) []*InstanceConfig {
	nodes, err := icq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InstanceConfig IDs.
func (icq *InstanceConfigQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := icq.Select(instanceconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (icq *InstanceConfigQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := icq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (icq *InstanceConfigQuery) Count(ctx context.Context) (int, error) {
	if err := icq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return icq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (icq *InstanceConfigQuery) CountX(ctx context.Context) int {
	count, err := icq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (icq *InstanceConfigQuery) Exist(ctx context.Context) (bool, error) {
	if err := icq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return icq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (icq *InstanceConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := icq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InstanceConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (icq *InstanceConfigQuery) Clone() *InstanceConfigQuery {
	if icq == nil {
		return nil
	}
	return &InstanceConfigQuery{
		config:       icq.config,
		limit:        icq.limit,
		offset:       icq.offset,
		order:        append([]OrderFunc{}, icq.order...),
		predicates:   append([]predicate.InstanceConfig{}, icq.predicates...),
		withInstance: icq.withInstance.Clone(),
		// clone intermediate query.
		sql:    icq.sql.Clone(),
		path:   icq.path,
		unique: icq.unique,
	}
}

// WithInstance tells the query-builder to eager-load the nodes that are connected to
// the "instance" edge. The optional arguments are used to configure the query builder of the edge.
func (icq *InstanceConfigQuery) WithInstance(opts ...func(*InstanceQuery)) *InstanceConfigQuery {
	query := &InstanceQuery{config: icq.config}
	for _, opt := range opts {
		opt(query)
	}
	icq.withInstance = query
	return icq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InstanceConfig.Query().
//		GroupBy(instanceconfig.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (icq *InstanceConfigQuery) GroupBy(field string, fields ...string) *InstanceConfigGroupBy {
	grbuild := &InstanceConfigGroupBy{config: icq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := icq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return icq.sqlQuery(ctx), nil
	}
	grbuild.label = instanceconfig.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.InstanceConfig.Query().
//		Select(instanceconfig.FieldKey).
//		Scan(ctx, &v)
func (icq *InstanceConfigQuery) Select(fields ...string) *InstanceConfigSelect {
	icq.fields = append(icq.fields, fields...)
	selbuild := &InstanceConfigSelect{InstanceConfigQuery: icq}
	selbuild.label = instanceconfig.Label
	selbuild.flds, selbuild.scan = &icq.fields, selbuild.Scan
	return selbuild
}

func (icq *InstanceConfigQuery) prepareQuery(ctx context.Context) error {
	for _, f := range icq.fields {
		if !instanceconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if icq.path != nil {
		prev, err := icq.path(ctx)
		if err != nil {
			return err
		}
		icq.sql = prev
	}
	return nil
}

func (icq *InstanceConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*InstanceConfig, error) {
	var (
		nodes       = []*InstanceConfig{}
		withFKs     = icq.withFKs
		_spec       = icq.querySpec()
		loadedTypes = [1]bool{
			icq.withInstance != nil,
		}
	)
	if icq.withInstance != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, instanceconfig.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*InstanceConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &InstanceConfig{config: icq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, icq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := icq.withInstance; query != nil {
		if err := icq.loadInstance(ctx, query, nodes, nil,
			func(n *InstanceConfig, e *Instance) { n.Edges.Instance = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (icq *InstanceConfigQuery) loadInstance(ctx context.Context, query *InstanceQuery, nodes []*InstanceConfig, init func(*InstanceConfig), assign func(*InstanceConfig, *Instance)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*InstanceConfig)
	for i := range nodes {
		if nodes[i].instance_configs == nil {
			continue
		}
		fk := *nodes[i].instance_configs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(instance.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "instance_configs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (icq *InstanceConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := icq.querySpec()
	_spec.Node.Columns = icq.fields
	if len(icq.fields) > 0 {
		_spec.Unique = icq.unique != nil && *icq.unique
	}
	return sqlgraph.CountNodes(ctx, icq.driver, _spec)
}

func (icq *InstanceConfigQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := icq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (icq *InstanceConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   instanceconfig.Table,
			Columns: instanceconfig.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: instanceconfig.FieldID,
			},
		},
		From:   icq.sql,
		Unique: true,
	}
	if unique := icq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := icq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instanceconfig.FieldID)
		for i := range fields {
			if fields[i] != instanceconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := icq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := icq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := icq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := icq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (icq *InstanceConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(icq.driver.Dialect())
	t1 := builder.Table(instanceconfig.Table)
	columns := icq.fields
	if len(columns) == 0 {
		columns = instanceconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if icq.sql != nil {
		selector = icq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if icq.unique != nil && *icq.unique {
		selector.Distinct()
	}
	for _, p := range icq.predicates {
		p(selector)
	}
	for _, p := range icq.order {
		p(selector)
	}
	if offset := icq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := icq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InstanceConfigGroupBy is the group-by builder for InstanceConfig entities.
type InstanceConfigGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (icgb *InstanceConfigGroupBy) Aggregate(fns ...AggregateFunc) *InstanceConfigGroupBy {
	icgb.fns = append(icgb.fns, fns...)
	return icgb
}

// Scan applies the group-by query and scans the result into the given value.
func (icgb *InstanceConfigGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := icgb.path(ctx)
	if err != nil {
		return err
	}
	icgb.sql = query
	return icgb.sqlScan(ctx, v)
}

func (icgb *InstanceConfigGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range icgb.fields {
		if !instanceconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := icgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := icgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (icgb *InstanceConfigGroupBy) sqlQuery() *sql.Selector {
	selector := icgb.sql.Select()
	aggregation := make([]string, 0, len(icgb.fns))
	for _, fn := range icgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(icgb.fields)+len(icgb.fns))
		for _, f := range icgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(icgb.fields...)...)
}

// InstanceConfigSelect is the builder for selecting fields of InstanceConfig entities.
type InstanceConfigSelect struct {
	*InstanceConfigQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ics *InstanceConfigSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ics.prepareQuery(ctx); err != nil {
		return err
	}
	ics.sql = ics.InstanceConfigQuery.sqlQuery(ctx)
	return ics.sqlScan(ctx, v)
}

func (ics *InstanceConfigSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ics.sql.Query()
	if err := ics.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
